name: flutter_common
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #https://caijinglong.github.io/json2dart/index_ch.html
  #flutter packages pub run build_runner build
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  fluttertoast: ^3.0.3 #https://pub.dartlang.org/packages/fluttertoast
  shared_preferences: ^0.5.3+4 # SP
  flutter_spinkit: ^3.1.0 #https://pub.dartlang.org/packages/flutter_spinkit
  connectivity: ^0.4.2 #https://pub.dartlang.org/packages/connectivity
  pull_to_refresh: ^1.1.6 #https://pub.dartlang.org/packages/pull_to_refresh
  dio: ^2.0.4 # https://github.com/flutterchina/dio
  rxdart: ^0.21.0  #rxdart https://github.com/ReactiveX/rxdart
  common_utils: ^1.1.1 # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  # https://caijinglong.github.io/json2dart/index_ch.html
  # flutter packages pub run build_runner build
  json_annotation: ^2.0.0 #https://pub.dartlang.org/packages/json_annotation
  fluro: ^1.4.0 #https://pub.dartlang.org/packages/fluro
  scoped_model: ^1.0.1 #https://pub.dartlang.org/packages/scoped_model
  device_info: ^0.4.0+1 #https://pub.dev/packages/device_info#-installing-tab-
  get_ip: ^0.3.0 #https://pub.dev/packages/get_ip#-installing-tab-
  devicelocale: ^0.1.1 #https://pub.dev/packages/devicelocale#-installing-tab-
  flutter_user_agent: ^1.0.1 #https://pub.dev/packages/flutter_user_agent#-installing-tab-
  path_provider: ^1.3.0 #https://pub.dev/packages/path_provider#-installing-tab-
  #flutter_statusbar_manager: ^1.0.2 #https://pub.dev/packages/flutter_statusbar_manager#-installing-tab-
  # 数据管理层
  provider: ^3.1.0 #https://pub.dev/packages/provider#-installing-tab-
  # 引导页
  intro_slider: ^2.2.8
  #键盘处理
  keyboard_actions: ^2.1.2
    # 集成图标库
    # FontAwesome 地址：http://www.fontawesome.com.cn/
    # Feather 地址：https://feathericons.com/
    # EvilIcons 地址：https://evil-icons.io/
    # AntDesign 地址：https://ant.design/components/icon/
    # Ionicons 地址：https://ionicons.com
    # Fontisto 地址：https://fontisto.com/icons
    # Foundation 地址：https://zurb:com/playground/foundation-icon-fonts-3
    # Octicons 地址：https://octicons.github.com/
  # SimpleLineIcons 地址：https://simplelineicons.github.io/
  flutter_vector_icons: ^0.2.1
  # 刷新加载控件
  flutter_easyrefresh: ^2.0.4
  # banner
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.8
  share: ^0.6.2+1
  expandable: ^3.0.0+1
  like_button: ^0.1.9
  # 调整屏幕和字体大小
  flutter_screenutil: ^0.6.0
  flutter_html: ^0.11.0
  flare_flutter: ^1.6.2
  amap_base_location: ^0.4.0+2
  scroll_to_index: ^1.0.2
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - assets/
    - assets/data/
    - images/
    - images/common/
